# Generated by Django 5.1.3 on 2024-12-09 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('standard', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fee_type_master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fee-Type-Master',
                'verbose_name_plural': 'Fee-Type-Master',
                'db_table': 'fee_type_master',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='fee_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.PositiveBigIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('standard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='standard.standard_master')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standard.academicyear')),
                ('fee_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.fee_type_master')),
            ],
            options={
                'verbose_name': 'Fee-Type',
                'verbose_name_plural': 'Fee-Type',
                'db_table': 'fee_type',
                'ordering': ['-created_at'],
                'unique_together': {('fee_master', 'standard', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fee_paid_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.students')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_fee', models.PositiveBigIntegerField(default=0)),
                ('amount_paid', models.PositiveBigIntegerField(default=0)),
                ('amount_waived', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.fee_type')),
                ('receipt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.receipt')),
            ],
        ),
        migrations.CreateModel(
            name='student_fees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_paid', models.PositiveBigIntegerField(default=0)),
                ('amount_waived', models.PositiveBigIntegerField(default=0)),
                ('is_assigned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.fee_type')),
                ('standard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='standard.standard_master')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.students')),
            ],
            options={
                'verbose_name': 'Student-Fee',
                'verbose_name_plural': 'Student-Fee',
                'db_table': 'student_fees',
                'ordering': ['-created_at'],
            },
        ),
    ]
