# Generated by Django 4.1.5 on 2024-07-04 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0002_alter_educationalyear_year_alter_exammarks_std_and_more'),
        ('standard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fee_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.PositiveBigIntegerField()),
                ('year', models.CharField(choices=[('2024', '2024'), ('2023', '2023'), ('2022', '2022'), ('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013'), ('2012', '2012'), ('2011', '2011'), ('2010', '2010'), ('2009', '2009'), ('2008', '2008'), ('2007', '2007'), ('2006', '2006'), ('2005', '2005'), ('2004', '2004'), ('2003', '2003'), ('2002', '2002'), ('2001', '2001'), ('2000', '2000')], max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fee-Type',
                'verbose_name_plural': 'Fee-Type',
                'db_table': 'fee_type',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='fee_type_master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fee-Type-Master',
                'verbose_name_plural': 'Fee-Type-Master',
                'db_table': 'fee_type_master',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='historical_fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13')], max_length=10)),
                ('year', models.CharField(choices=[('2024', '2024'), ('2023', '2023'), ('2022', '2022'), ('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013'), ('2012', '2012'), ('2011', '2011'), ('2010', '2010'), ('2009', '2009'), ('2008', '2008'), ('2007', '2007'), ('2006', '2006'), ('2005', '2005'), ('2004', '2004'), ('2003', '2003'), ('2002', '2002'), ('2001', '2001'), ('2000', '2000')], max_length=10)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('receipt_no', models.CharField(max_length=10)),
                ('fee_type', models.CharField(choices=[('સ્કૂલ ફી', 'સ્કૂલ ફી'), ('bus fee', 'bus fee'), ('form fee', 'form fee'), ('other', 'other')], max_length=10)),
                ('amount', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Historical-Fee',
                'verbose_name_plural': 'Historical-Fee',
                'db_table': 'historical_fees',
                'ordering': ['standard'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fee_paid_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.students')),
            ],
        ),
        migrations.CreateModel(
            name='student_fees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_paid', models.PositiveBigIntegerField(default=0)),
                ('amount_waived', models.PositiveBigIntegerField(default=0)),
                ('is_assigned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.fee_type')),
                ('standard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='standard.standard_master')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.students')),
            ],
            options={
                'verbose_name': 'Student-Fee',
                'verbose_name_plural': 'Student-Fee',
                'db_table': 'student_fees',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_fee', models.PositiveBigIntegerField(default=0)),
                ('amount_paid', models.PositiveBigIntegerField(default=0)),
                ('amount_waived', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.fee_type')),
                ('receipt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.receipt')),
            ],
        ),
        migrations.AddField(
            model_name='fee_type',
            name='fee_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.fee_type_master'),
        ),
        migrations.AddField(
            model_name='fee_type',
            name='standard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='standard.standard_master'),
        ),
    ]
