# Generated by Django 5.0.6 on 2024-10-28 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('standard', '0002_academicyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee_type',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='standard.academicyear'),
            preserve_default=False,
        ),
    ]
