# Generated by Django 5.0.6 on 2024-10-28 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_fee_type_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='historical_fees',
        ),
    ]
