# Generated by Django 5.0.6 on 2024-11-27 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_delete_historical_fees'),
        ('standard', '0005_standard_master_school_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fee_type',
            unique_together={('fee_master', 'standard', 'year')},
        ),
    ]
