# Generated by Django 5.0.6 on 2024-11-14 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_blockeduser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlockedUser',
        ),
    ]
