# Generated by Django 5.1.3 on 2024-12-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_chatmessage_deleted_by_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
