# Generated by Django 5.1.3 on 2024-12-06 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_chatmessage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='image',
        ),
    ]
