# Generated by Django 5.0.6 on 2024-11-26 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0003_standard_master_school_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standard_master',
            name='school_type',
        ),
    ]
