# Generated by Django 5.0.6 on 2024-11-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0004_remove_standard_master_school_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard_master',
            name='school_type',
            field=models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('High Secondary', 'High Secondary')], default='Primary', max_length=20),
        ),
    ]
