# Generated by Django 5.1.3 on 2024-12-09 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('standard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsStdMultiList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grno', models.IntegerField()),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('year', models.CharField(choices=[('2030', '2030'), ('2029', '2029'), ('2028', '2028'), ('2027', '2027'), ('2026', '2026'), ('2025', '2025'), ('2024', '2024'), ('2023', '2023'), ('2022', '2022'), ('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013'), ('2012', '2012'), ('2011', '2011'), ('2010', '2010'), ('2009', '2009'), ('2008', '2008'), ('2007', '2007'), ('2006', '2006'), ('2005', '2005'), ('2004', '2004'), ('2003', '2003'), ('2002', '2002'), ('2001', '2001'), ('2000', '2000')], max_length=50)),
                ('standard', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('Balvatika', 'Balvatika')], max_length=10)),
                ('is_active', models.BooleanField(default=False)),
                ('is_active_year', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentsUpdatesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('year', models.CharField(choices=[('2030', '2030'), ('2029', '2029'), ('2028', '2028'), ('2027', '2027'), ('2026', '2026'), ('2025', '2025'), ('2024', '2024'), ('2023', '2023'), ('2022', '2022'), ('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013'), ('2012', '2012'), ('2011', '2011'), ('2010', '2010'), ('2009', '2009'), ('2008', '2008'), ('2007', '2007'), ('2006', '2006'), ('2005', '2005'), ('2004', '2004'), ('2003', '2003'), ('2002', '2002'), ('2001', '2001'), ('2000', '2000')], max_length=50)),
                ('standard', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('Balvatika', 'Balvatika')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('update_date', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2030', '2030'), ('2029', '2029'), ('2028', '2028'), ('2027', '2027'), ('2026', '2026'), ('2025', '2025'), ('2024', '2024'), ('2023', '2023'), ('2022', '2022'), ('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013'), ('2012', '2012'), ('2011', '2011'), ('2010', '2010'), ('2009', '2009'), ('2008', '2008'), ('2007', '2007'), ('2006', '2006'), ('2005', '2005'), ('2004', '2004'), ('2003', '2003'), ('2002', '2002'), ('2001', '2001'), ('2000', '2000')], max_length=50)),
                ('standard', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('Balvatika', 'Balvatika')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ExamMarksTemplateAdd',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_marks', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_marks_templates', to='standard.standard_master')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grno', models.IntegerField(unique=True)),
                ('student_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('gender', models.CharField(choices=[('કુમાર', 'કુમાર'), ('કન્યા', 'કન્યા')], max_length=10)),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('district', models.CharField(max_length=50, null=True)),
                ('section', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=2, null=True)),
                ('last_school', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('admission_std', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('Balvatika', 'Balvatika')], max_length=10)),
                ('admission_date', models.CharField(choices=[('2030', '2030'), ('2029', '2029'), ('2028', '2028'), ('2027', '2027'), ('2026', '2026'), ('2025', '2025'), ('2024', '2024'), ('2023', '2023'), ('2022', '2022'), ('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013'), ('2012', '2012'), ('2011', '2011'), ('2010', '2010'), ('2009', '2009'), ('2008', '2008'), ('2007', '2007'), ('2006', '2006'), ('2005', '2005'), ('2004', '2004'), ('2003', '2003'), ('2002', '2002'), ('2001', '2001'), ('2000', '2000')], max_length=50)),
                ('left_school_std', models.CharField(blank=True, max_length=2, null=True)),
                ('left_school_date', models.DateField(blank=True, null=True)),
                ('religion', models.CharField(choices=[('હિન્દુ', 'હિન્દુ'), ('જૈન', 'જૈન'), ('મુસ્લિમ', 'મુસ્લિમ'), ('શિખ', 'શિખ'), ('ખ્રિસ્તી', 'ખ્રિસ્તી')], max_length=50)),
                ('category', models.CharField(choices=[('જનરલ', 'જનરલ'), ('ઓ.બી.સી.', 'ઓ.બી.સી.'), ('એસસી/એસટી', 'એસસી/એસટી'), ('ઇ.ડબ્લ્યુ.એસ.', 'ઇ.ડબ્લ્યુ.એસ.')], max_length=50)),
                ('caste', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('udise_no', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('aadhar_no', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('account_no', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('name_on_passbook', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('bank_address', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('reason', models.CharField(blank=True, default='અન્યત્રે જવાથી', max_length=100, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('assesment', models.IntegerField(default=1)),
                ('progress', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('ચાલુ', 'ચાલુ'), ('કમી', 'કમી')], default='ચાલુ', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standard.academicyear')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standard.standard_master')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='SchoolStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2030', '2030'), ('2029', '2029'), ('2028', '2028'), ('2027', '2027'), ('2026', '2026'), ('2025', '2025'), ('2024', '2024'), ('2023', '2023'), ('2022', '2022'), ('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013'), ('2012', '2012'), ('2011', '2011'), ('2010', '2010'), ('2009', '2009'), ('2008', '2008'), ('2007', '2007'), ('2006', '2006'), ('2005', '2005'), ('2004', '2004'), ('2003', '2003'), ('2002', '2002'), ('2001', '2001'), ('2000', '2000')], max_length=50)),
                ('standard', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('Balvatika', 'Balvatika')], max_length=14)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('update_date', models.CharField(default='', max_length=100)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.students')),
            ],
        ),
        migrations.CreateModel(
            name='ExamMarkAssingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.IntegerField(null=True)),
                ('standard', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('Balvatika', 'Balvatika')], max_length=14)),
                ('total_marks', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('કુમાર', 'કુમાર'), ('કન્યા', 'કન્યા')], max_length=10, null=True)),
                ('mark', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.students')),
            ],
        ),
    ]
