# Generated by Django 5.0.6 on 2024-10-28 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_students_academic_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamMarks',
        ),
    ]
