# Generated by Django 5.0.6 on 2024-07-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_educationalyear_year_alter_exammarks_std_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamMarksTemplateAdd',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('standard', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13')], max_length=14)),
                ('total_marks', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
