# Generated by Django 5.0.6 on 2024-07-16 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_exammarkstemplateadd'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamMarkAssingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.IntegerField(null=True)),
                ('standard', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13')], max_length=14)),
                ('total_marks', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('કુમાર', 'કુમાર'), ('કન્યા', 'કન્યા')], max_length=10, null=True)),
                ('mark', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.students')),
            ],
        ),
    ]
