# Generated by Django 5.1.3 on 2024-12-09 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentsupdatestandardandacademicyearhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentsUpdateStandardAndAcademicYearHistory',
        ),
    ]
