# Generated by Django 5.0.6 on 2024-10-28 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_delete_exammarks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EducationalYear',
        ),
    ]
