# Generated by Django 5.1.3 on 2024-12-10 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0001_initial'),
        ('student', '0004_delete_studentsupdatestandardandacademicyearhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUpdateStdAcademicHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standard.academicyear')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standard.standard_master')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.students')),
            ],
        ),
    ]
