# Generated by Django 5.0.6 on 2024-11-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_delete_educationalyear'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentsUpdateList',
        ),
    ]
