# Generated by Django 5.1.3 on 2024-12-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_exammarkassingdata_standard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentupdatestdacademichistory',
            name='section',
            field=models.TextField(blank=True),
        ),
    ]
