# Generated by Django 5.1.3 on 2024-12-02 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_students_student_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='student_img',
        ),
    ]
