# Generated by Django 5.1.3 on 2024-12-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_remove_students_student_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='student_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
