# Generated by Django 5.1.3 on 2024-12-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_studentupdatestdacademichistory_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentupdatestdacademichistory',
            name='section',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
