# Generated by Django 5.1.3 on 2025-01-15 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_students_roll_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='roll_no',
        ),
    ]
