# Generated by Django 5.1.3 on 2025-01-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_remove_students_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='roll_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
