# Generated by Django 5.1.3 on 2025-01-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_students_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='roll_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
