# Generated by Django 5.1.3 on 2025-01-16 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_alter_students_roll_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'permissions': [('can_view_students', 'Can view students list'), ('can_view_student_details', 'Can view student details'), ('can_add_student', 'Can add student'), ('can_edit_student', 'Can edit student'), ('can_delete_student', 'Can delete student')], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
    ]
