# Generated by Django 5.1.3 on 2025-05-10 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_alter_students_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
    ]
